#!/usr/bin/env bash
#
# Feel free to add new aliases or edit the default ones as
# much as you want, but always watch the consequences. It
# is recommended to keep these aliases without modifying them
# as some dotfiles may rely on them.
#
# @author losedavidpb

script_path="${BASH_SOURCE:-$0}"
abs_script_path="$(realpath "${script_path}")"
_shell_abs_script_directory="$(dirname "${abs_script_path}")"
unset script_path abs_script_path

source $_shell_abs_script_directory/exports

# Aliases for package manager.
#
# It is important to notice that these aliases
# would be defined as expected as long as the
# machine has installed an available one
case $PACKAGE_MANAGER in
	"apt")
		alias install="sudo apt install"
		alias uninstall="sudo apt remove"
		alias update="sudo apt update"
		alias upgrade="sudo apt upgrade"
		alias list_all_packs="apt list"
		alias search_pack="apt list | egrep"
	;;

	"apt-get")
		alias install="sudo apt-get install"
		alias uninstall="sudo apt-get remove"
		alias update="sudo apt-get update"
		alias update="sudo apt-get upgrade"
		alias list_all_packs="apt list"
		alias search_pack="apt list | egrep"
	;;

	"dnf")
		alias install="sudo dnf install"
		alias uninstall="sudo dnf remove"
		alias update="sudo dnf check-update"
		alias upgrade="sudo dnf upgrade"
		alias list_all_packs="dnf list installed"
		alias search_pack="dnf search"
	;;

	"pacman")
		alias install="sudo pacman -Syyu"
		alias uninstall="sudo pacman -Rns"
		alias update="sudo pacman -Syyu"
		alias upgrade="sudo pacman -Syyu"
		alias list_all_packs="pacman -Q"
		alias search_pack="pacman -Q | egrep"
	;;

	"brew")
		alias install="brew install"
		alias uninstall="brew uninstall"
		alias update="brew update"
		alias upgrade="brew upgrade"
		alias list_all_packs="brew list"
		alias search_pack="brew search"
	;;

	"yum")
		alias install="sudo yum install"
		alias uninstall="sudo yum remove"
		alias update="sudo yum update"
		alias upgrade="sudo yum upgrade"
		alias list_all_packs="yum list"
		alias search_pack="yum list | egrep"
	;;

	"zypper")
		alias install="sudo zypper ar"
		alias uninstall="sudo zypper rr"
		alias update="sudo zypper refresh"
		alias upgrade="sudo zypper dist-upgrade"
		alias list_all_packs="zypper repos"
		alias search_pack="zypper repos | egrep"
	;;

	"apk")
		alias install="sudo apk add"
		alias uninstall="sudo apk del"
		alias update="sudo apk update"
		alias upgrade="sudo apk upgrade"
		alias list_all_packs="apk search -v"
		alias search_pack="apk search -v | egrep"
	;;

	"emerger")
		alias install="sudo emerge"
		alias uninstall="sudo emerge -C"
		alias update="sudo emerge -uDp world"
		alias upgrade="sudo emerge -uDp world"
		alias list_all_packs="emerge -s"
		alias search_pack="emerge -s | egrep"
	;;

	"xbps-install")
		alias install="sudo xbps-install"
		alias uninstall="sudo xbps-remove -R"
		alias update="sudo xbps-install -S"
		alias upgrade="sudo xbps-install -Su"
		alias list_all_packs="xbps-query -l"
		alias search_pack="xbps-query -Rs"
	;;

	"pkg")
		alias install="sudo pkg install"
		alias uninstall="sudo pkg delete"
		alias update="sudo pkg update"
		alias upgrade="sudo pkg upgrade"
		alias list_all_packs="pkg info"
		alias search_pack="pkg search"
	;;

	*)
		alias install="echo \"error: command not available\""
		alias uninstall="echo \"error: command not available\""
		alias update="echo \"error: command not available\""
		alias upgrade="echo \"error: command not available\""
		alias list_all_packs="echo \"error: command not available\""
		alias search_pack="echo \"error: command not available\""
	;;
esac

# === Directory navigation ===
alias .="cd ../"                            # go back just once
alias ..="cd ../.."                         # go back twice

# === User directories ===
alias home="cd ~"                           # shortcut to home directory
alias desk="cd ~/Desktop"                   # shortcut to desktop
alias dl="cd ~/Downloads"                   # shortcut to downloads
alias docs="cd ~/Documents"                 # shortcut to documents
alias pic="cd ~/Pictures"                   # shortcut to pictures
alias music="cd ~/Music"                    # shortcut to music
alias vid="cd ~/Videos"                     # shortcut to videos
alias cfg="cd ~/.config"                    # shortcut to .config

# === WSL directories ===
alias wslfs="cd $WSL_FS"                    # shortcut to WSL file system
alias wslhome="cd $WSL_HOME"                # shortcut to WSL home directory
alias wsldesk="cd $WSL_HOME/Desktop"        # shortcut to WSL desktop
alias wsldl="cd $WSL_HOME/Downloads"        # shortcut to WSL downloads
alias wsldocs="cd $WSL_HOME/Documents"      # shortcut to WSL documents
alias wslpic="cd $WSL_HOME/Pictures"        # shortcut to WSL pictures
alias wslmusic="cd $WSL_HOME/Music"         # shortcut to WSL music
alias wslvid="cd $WSL_HOME/Videos"          # shortcut to WSL videos
alias wslapps="cd $WSL_APPS"                # shortcut to WSL applications

# === File listing ===
alias ls="ls --color=auto -F"                # show current files with colors
alias lls="ls -l --color=auto -F"            # show detailed current files with colors
alias lsd="ls -lCd .?* --color=auto -F"      # show current dotfiles with colors
alias llsd="ls -ld .?* --color=auto -F"      # show detailed current dotfiles with colors
alias lsa="ls -laC --color=auto -F"          # show all current files with colors
alias llsa="ls -la --color=auto -F"          # show all detailed current files with colors

# === Search utilities ===
alias grep='grep --colour=auto'              # greep with colors
alias egrep='egrep --colour=auto'            # egreep with colors
alias fgrep='fgrep --colour=auto'            # fgreep with colors

# === System utilities ===
alias df="df -h"                             # human-readable sizes
alias dfdev="df -Th | grep '^/dev'"          # human-readable sizes for devs
alias free="free -m"                         # show sizes in MB
alias more=less                              # both commands do the same
alias cls="clear"                            # clear current terminal

# === File management ===
alias cpi="cp -i"                            # confirm before overwriting something
alias cpr="cp -r"							 # copy files and directories
alias rrm="rm -fR "                          # remove all files inside current directory

# === System information ===
alias sysinfo="neofetch --source ~/.config/neofetch/ascii_icon --colors 133 249 255 133 255 255"
alias cpuinfo="grep 'model name' /proc/cpuinfo | cut -d ":" -f 2 | uniq"
alias osinfo="echo $(uname -o) $(uname -m)"
alias uptime="uptime -p | cut -c 4-"
alias kernelinfo="uname -r"
alias ddate='date +"%R - %a, %B %d, %Y"'

# === Git shortcuts ===
alias ga='git add -A'
alias gc='git commit -m'
alias gcl='git clone'
alias gco='git checkout'
alias gpr='git prune'
alias gd='git diff'
alias gp='git push'
alias gpo='git push origin'
alias gs='git status'
alias gba='git branch -a'
alias gpom='git push origin master'
alias gphm='git push heroku master'
alias gnb='git checkout -b'
alias gbdelall='git branch | grep -v -e master -e dev | xargs git branch -D'